// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: competitions.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteCompetition = `-- name: DeleteCompetition :one
DELETE FROM competitions
WHERE id = $1
RETURNING id, name, status, start_time, winner, min_rounds, created_at
`

type DeleteCompetitionParams struct {
	ID uuid.UUID `json:"id"`
}

func (q *Queries) DeleteCompetition(ctx context.Context, arg DeleteCompetitionParams) (Competition, error) {
	row := q.db.QueryRow(ctx, deleteCompetition, arg.ID)
	var i Competition
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.StartTime,
		&i.Winner,
		&i.MinRounds,
		&i.CreatedAt,
	)
	return i, err
}

const findAllCompetitions = `-- name: FindAllCompetitions :many
SELECT id, name, status, start_time, winner, min_rounds, created_at FROM competitions ORDER BY created_at DESC
`

func (q *Queries) FindAllCompetitions(ctx context.Context) ([]Competition, error) {
	rows, err := q.db.Query(ctx, findAllCompetitions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Competition{}
	for rows.Next() {
		var i Competition
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.StartTime,
			&i.Winner,
			&i.MinRounds,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAllCompetitionsToStart = `-- name: FindAllCompetitionsToStart :many
SELECT id, name, status, start_time, winner, min_rounds, created_at FROM competitions
WHERE
  status = 'awaiting' AND
  start_time < CURRENT_TIMESTAMP 
ORDER BY start_time ASC
`

func (q *Queries) FindAllCompetitionsToStart(ctx context.Context) ([]Competition, error) {
	rows, err := q.db.Query(ctx, findAllCompetitionsToStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Competition{}
	for rows.Next() {
		var i Competition
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.StartTime,
			&i.Winner,
			&i.MinRounds,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAllRunningCompetitions = `-- name: FindAllRunningCompetitions :many
SELECT id, name, status, start_time, winner, min_rounds, created_at FROM competitions WHERE status = 'running' ORDER BY created_at ASC
`

func (q *Queries) FindAllRunningCompetitions(ctx context.Context) ([]Competition, error) {
	rows, err := q.db.Query(ctx, findAllRunningCompetitions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Competition{}
	for rows.Next() {
		var i Competition
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.StartTime,
			&i.Winner,
			&i.MinRounds,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCompetition = `-- name: InsertCompetition :one
INSERT INTO competitions (
  name,
  start_time
) VALUES ( $1, $2 )
RETURNING id, name, status, start_time, winner, min_rounds, created_at
`

type InsertCompetitionParams struct {
	Name      string    `json:"name"`
	StartTime time.Time `json:"start_time"`
}

func (q *Queries) InsertCompetition(ctx context.Context, arg InsertCompetitionParams) (Competition, error) {
	row := q.db.QueryRow(ctx, insertCompetition, arg.Name, arg.StartTime)
	var i Competition
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.StartTime,
		&i.Winner,
		&i.MinRounds,
		&i.CreatedAt,
	)
	return i, err
}

const renameCompetition = `-- name: RenameCompetition :one
UPDATE competitions
SET name = $2
WHERE id = $1
RETURNING id, name, status, start_time, winner, min_rounds, created_at
`

type RenameCompetitionParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) RenameCompetition(ctx context.Context, arg RenameCompetitionParams) (Competition, error) {
	row := q.db.QueryRow(ctx, renameCompetition, arg.ID, arg.Name)
	var i Competition
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.StartTime,
		&i.Winner,
		&i.MinRounds,
		&i.CreatedAt,
	)
	return i, err
}

const setCompetitionStatus = `-- name: SetCompetitionStatus :one
UPDATE competitions
SET
  status = $2
WHERE id = $1
RETURNING id, name, status, start_time, winner, min_rounds, created_at
`

type SetCompetitionStatusParams struct {
	ID     uuid.UUID  `json:"id"`
	Status UnitStatus `json:"status"`
}

func (q *Queries) SetCompetitionStatus(ctx context.Context, arg SetCompetitionStatusParams) (Competition, error) {
	row := q.db.QueryRow(ctx, setCompetitionStatus, arg.ID, arg.Status)
	var i Competition
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.StartTime,
		&i.Winner,
		&i.MinRounds,
		&i.CreatedAt,
	)
	return i, err
}

const setCompetitionWinner = `-- name: SetCompetitionWinner :one
UPDATE competitions
SET
  winner = $2
WHERE id = $1
RETURNING id, name, status, start_time, winner, min_rounds, created_at
`

type SetCompetitionWinnerParams struct {
	ID     uuid.UUID  `json:"id"`
	Winner *uuid.UUID `json:"winner"`
}

func (q *Queries) SetCompetitionWinner(ctx context.Context, arg SetCompetitionWinnerParams) (Competition, error) {
	row := q.db.QueryRow(ctx, setCompetitionWinner, arg.ID, arg.Winner)
	var i Competition
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.StartTime,
		&i.Winner,
		&i.MinRounds,
		&i.CreatedAt,
	)
	return i, err
}
