// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inscriptions.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const getActiveCompetitionInscriptions = `-- name: GetActiveCompetitionInscriptions :many
SELECT id, competition, participant, points, active, created_at FROM inscriptions
WHERE competition = $1 AND active = True
ORDER BY points
`

type GetActiveCompetitionInscriptionsParams struct {
	Competition uuid.UUID `json:"competition"`
}

func (q *Queries) GetActiveCompetitionInscriptions(ctx context.Context, arg GetActiveCompetitionInscriptionsParams) ([]Inscription, error) {
	rows, err := q.db.Query(ctx, getActiveCompetitionInscriptions, arg.Competition)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Inscription{}
	for rows.Next() {
		var i Inscription
		if err := rows.Scan(
			&i.ID,
			&i.Competition,
			&i.Participant,
			&i.Points,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserInscriptions = `-- name: GetUserInscriptions :many
SELECT id, competition, participant, points, active, created_at FROM inscriptions
WHERE participant = $1
`

type GetUserInscriptionsParams struct {
	Participant uuid.UUID `json:"participant"`
}

func (q *Queries) GetUserInscriptions(ctx context.Context, arg GetUserInscriptionsParams) ([]Inscription, error) {
	rows, err := q.db.Query(ctx, getUserInscriptions, arg.Participant)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Inscription{}
	for rows.Next() {
		var i Inscription
		if err := rows.Scan(
			&i.ID,
			&i.Competition,
			&i.Participant,
			&i.Points,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertInscription = `-- name: InsertInscription :one
INSERT INTO inscriptions (
  competition,
  participant
) VALUES ( $1, $2 )
RETURNING id, competition, participant, points, active, created_at
`

type InsertInscriptionParams struct {
	Competition uuid.UUID `json:"competition"`
	Participant uuid.UUID `json:"participant"`
}

func (q *Queries) InsertInscription(ctx context.Context, arg InsertInscriptionParams) (Inscription, error) {
	row := q.db.QueryRow(ctx, insertInscription, arg.Competition, arg.Participant)
	var i Inscription
	err := row.Scan(
		&i.ID,
		&i.Competition,
		&i.Participant,
		&i.Points,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}
