// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inscriptions.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getCompetitionInscriptions = `-- name: GetCompetitionInscriptions :many
SELECT i.id, i.competition, i.participant, i.created_at, u.id AS user_id
FROM inscriptions i
JOIN users u ON i.participant = u.id
WHERE i.competition = $1
ORDER BY i.created_at ASC
`

type GetCompetitionInscriptionsParams struct {
	Competition uuid.UUID `json:"competition"`
}

type GetCompetitionInscriptionsRow struct {
	ID          uuid.UUID        `json:"id"`
	Competition uuid.UUID        `json:"competition"`
	Participant uuid.UUID        `json:"participant"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UserID      uuid.UUID        `json:"user_id"`
}

func (q *Queries) GetCompetitionInscriptions(ctx context.Context, arg GetCompetitionInscriptionsParams) ([]GetCompetitionInscriptionsRow, error) {
	rows, err := q.db.Query(ctx, getCompetitionInscriptions, arg.Competition)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCompetitionInscriptionsRow{}
	for rows.Next() {
		var i GetCompetitionInscriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Competition,
			&i.Participant,
			&i.CreatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserInscriptions = `-- name: GetUserInscriptions :many
SELECT id, competition, participant, created_at FROM inscriptions
WHERE participant = $1
`

type GetUserInscriptionsParams struct {
	Participant uuid.UUID `json:"participant"`
}

func (q *Queries) GetUserInscriptions(ctx context.Context, arg GetUserInscriptionsParams) ([]Inscription, error) {
	rows, err := q.db.Query(ctx, getUserInscriptions, arg.Participant)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Inscription{}
	for rows.Next() {
		var i Inscription
		if err := rows.Scan(
			&i.ID,
			&i.Competition,
			&i.Participant,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertInscription = `-- name: InsertInscription :one
INSERT INTO inscriptions (
  competition,
  participant
) VALUES ( $1, $2 )
RETURNING id, competition, participant, created_at
`

type InsertInscriptionParams struct {
	Competition uuid.UUID `json:"competition"`
	Participant uuid.UUID `json:"participant"`
}

func (q *Queries) InsertInscription(ctx context.Context, arg InsertInscriptionParams) (Inscription, error) {
	row := q.db.QueryRow(ctx, insertInscription, arg.Competition, arg.Participant)
	var i Inscription
	err := row.Scan(
		&i.ID,
		&i.Competition,
		&i.Participant,
		&i.CreatedAt,
	)
	return i, err
}
