// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: matches.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const findAllMatches = `-- name: FindAllMatches :many
SELECT id, competition, winner, user1, user2, prev, created_at FROM matches ORDER BY created_at DESC
`

func (q *Queries) FindAllMatches(ctx context.Context) ([]Match, error) {
	rows, err := q.db.Query(ctx, findAllMatches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Match{}
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.Competition,
			&i.Winner,
			&i.User1,
			&i.User2,
			&i.Prev,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMatch = `-- name: InsertMatch :one
INSERT INTO matches (
  competition,
  user1,
  user2,
  prev -- TODO: replace prev with next
) VALUES ( $1, $2, $3, $4 )
RETURNING id, competition, winner, user1, user2, prev, created_at
`

type InsertMatchParams struct {
	Competition uuid.UUID  `json:"competition"`
	User1       uuid.UUID  `json:"user1"`
	User2       *uuid.UUID `json:"user2"`
	Prev        *uuid.UUID `json:"prev"`
}

func (q *Queries) InsertMatch(ctx context.Context, arg InsertMatchParams) (Match, error) {
	row := q.db.QueryRow(ctx, insertMatch,
		arg.Competition,
		arg.User1,
		arg.User2,
		arg.Prev,
	)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.Competition,
		&i.Winner,
		&i.User1,
		&i.User2,
		&i.Prev,
		&i.CreatedAt,
	)
	return i, err
}
