// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: matches.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const findAllMatches = `-- name: FindAllMatches :many
SELECT id, competition, winner, user1, user2, next, status, created_at FROM matches ORDER BY created_at DESC
`

func (q *Queries) FindAllMatches(ctx context.Context) ([]Match, error) {
	rows, err := q.db.Query(ctx, findAllMatches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Match{}
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.Competition,
			&i.Winner,
			&i.User1,
			&i.User2,
			&i.Next,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAllRunningMatches = `-- name: FindAllRunningMatches :many
SELECT id, name, status, created_at FROM competitions WHERE status = 'running' ORDER BY created_at ASC
`

func (q *Queries) FindAllRunningMatches(ctx context.Context) ([]Competition, error) {
	rows, err := q.db.Query(ctx, findAllRunningMatches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Competition{}
	for rows.Next() {
		var i Competition
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMatch = `-- name: InsertMatch :one
INSERT INTO matches (
  competition,
  user1,
  user2,
  next
) VALUES ( $1, $2, $3, $4 )
RETURNING id, competition, winner, user1, user2, next, status, created_at
`

type InsertMatchParams struct {
	Competition uuid.UUID  `json:"competition"`
	User1       uuid.UUID  `json:"user1"`
	User2       *uuid.UUID `json:"user2"`
	Next        *uuid.UUID `json:"next"`
}

func (q *Queries) InsertMatch(ctx context.Context, arg InsertMatchParams) (Match, error) {
	row := q.db.QueryRow(ctx, insertMatch,
		arg.Competition,
		arg.User1,
		arg.User2,
		arg.Next,
	)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.Competition,
		&i.Winner,
		&i.User1,
		&i.User2,
		&i.Next,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
