// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: matches.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const findAllMatches = `-- name: FindAllMatches :many
SELECT id, name, competition, start_time, end_time, winner, user1, user2, prev, created_at FROM matches ORDER BY created_at DESC
`

func (q *Queries) FindAllMatches(ctx context.Context) ([]Match, error) {
	rows, err := q.db.Query(ctx, findAllMatches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Match{}
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Competition,
			&i.StartTime,
			&i.EndTime,
			&i.Winner,
			&i.User1,
			&i.User2,
			&i.Prev,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMatch = `-- name: InsertMatch :one
INSERT INTO matches (
  name,
  competition,
  start_time,
  end_time,
  user1,
  user2,
  prev
) VALUES ( $1, $2, $3, $4, $5, $6, $7 )
RETURNING id, name, competition, start_time, end_time, winner, user1, user2, prev, created_at
`

type InsertMatchParams struct {
	Name        string             `json:"name"`
	Competition uuid.UUID          `json:"competition"`
	StartTime   pgtype.Timestamptz `json:"start_time"`
	EndTime     pgtype.Timestamptz `json:"end_time"`
	User1       uuid.UUID          `json:"user1"`
	User2       pgtype.UUID        `json:"user2"`
	Prev        pgtype.UUID        `json:"prev"`
}

func (q *Queries) InsertMatch(ctx context.Context, arg InsertMatchParams) (Match, error) {
	row := q.db.QueryRow(ctx, insertMatch,
		arg.Name,
		arg.Competition,
		arg.StartTime,
		arg.EndTime,
		arg.User1,
		arg.User2,
		arg.Prev,
	)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Competition,
		&i.StartTime,
		&i.EndTime,
		&i.Winner,
		&i.User1,
		&i.User2,
		&i.Prev,
		&i.CreatedAt,
	)
	return i, err
}
