// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Role string

const (
	RoleParticipant Role = "participant"
	RoleAdmin       Role = "admin"
)

func (e *Role) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Role(s)
	case string:
		*e = Role(s)
	default:
		return fmt.Errorf("unsupported scan type for Role: %T", src)
	}
	return nil
}

type NullRole struct {
	Role  Role `json:"role"`
	Valid bool `json:"valid"` // Valid is true if Role is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRole) Scan(value interface{}) error {
	if value == nil {
		ns.Role, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Role.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Role), nil
}

type UnitStatus string

const (
	UnitStatusAwaiting  UnitStatus = "awaiting"
	UnitStatusRunning   UnitStatus = "running"
	UnitStatusCompleted UnitStatus = "completed"
)

func (e *UnitStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UnitStatus(s)
	case string:
		*e = UnitStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UnitStatus: %T", src)
	}
	return nil
}

type NullUnitStatus struct {
	UnitStatus UnitStatus `json:"unit_status"`
	Valid      bool       `json:"valid"` // Valid is true if UnitStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUnitStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UnitStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UnitStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUnitStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UnitStatus), nil
}

type Competition struct {
	ID        uuid.UUID        `json:"id"`
	Name      string           `json:"name"`
	Status    UnitStatus       `json:"status"`
	StartTime time.Time        `json:"start_time"`
	Winner    *uuid.UUID       `json:"winner"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Inscription struct {
	ID          uuid.UUID        `json:"id"`
	Competition uuid.UUID        `json:"competition"`
	Participant uuid.UUID        `json:"participant"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type Match struct {
	ID          uuid.UUID        `json:"id"`
	Competition uuid.UUID        `json:"competition"`
	Winner      *uuid.UUID       `json:"winner"`
	User1       uuid.UUID        `json:"user1"`
	User2       *uuid.UUID       `json:"user2"`
	Next        *uuid.UUID       `json:"next"`
	Status      UnitStatus       `json:"status"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type Round struct {
	ID        uuid.UUID        `json:"id"`
	Task      uuid.UUID        `json:"task"`
	Match     uuid.UUID        `json:"match"`
	StartTime time.Time        `json:"start_time"`
	EndTime   time.Time        `json:"end_time"`
	Winner    *uuid.UUID       `json:"winner"`
	Status    UnitStatus       `json:"status"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Task struct {
	ID        uuid.UUID        `json:"id"`
	Name      string           `json:"name"`
	Details   string           `json:"details"`
	Points    int32            `json:"points"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type TaskOrder struct {
	ID          uuid.UUID        `json:"id"`
	Competition uuid.UUID        `json:"competition"`
	Task        uuid.UUID        `json:"task"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID        uuid.UUID        `json:"id"`
	Name      string           `json:"name"`
	Email     string           `json:"email"`
	Password  string           `json:"password"`
	Role      Role             `json:"role"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
