// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Role string

const (
	RoleParticipant Role = "participant"
	RoleAdmin       Role = "admin"
)

func (e *Role) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Role(s)
	case string:
		*e = Role(s)
	default:
		return fmt.Errorf("unsupported scan type for Role: %T", src)
	}
	return nil
}

type NullRole struct {
	Role  Role `json:"role"`
	Valid bool `json:"valid"` // Valid is true if Role is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRole) Scan(value interface{}) error {
	if value == nil {
		ns.Role, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Role.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Role), nil
}

type Competition struct {
	ID        uuid.UUID        `json:"id"`
	Name      string           `json:"name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Match struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Competition uuid.UUID          `json:"competition"`
	StartTime   pgtype.Timestamptz `json:"start_time"`
	EndTime     pgtype.Timestamptz `json:"end_time"`
	Winner      pgtype.UUID        `json:"winner"`
	User1       uuid.UUID          `json:"user1"`
	User2       pgtype.UUID        `json:"user2"`
	Prev        pgtype.UUID        `json:"prev"`
	CreatedAt   pgtype.Timestamp   `json:"created_at"`
}

type Round struct {
	ID        uuid.UUID        `json:"id"`
	Name      string           `json:"name"`
	Match     uuid.UUID        `json:"match"`
	Winner    pgtype.UUID      `json:"winner"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Task struct {
	ID          uuid.UUID        `json:"id"`
	Name        string           `json:"name"`
	Details     string           `json:"details"`
	Competition uuid.UUID        `json:"competition"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID          uuid.UUID        `json:"id"`
	Name        string           `json:"name"`
	Email       string           `json:"email"`
	Password    string           `json:"password"`
	Role        Role             `json:"role"`
	Competition uuid.UUID        `json:"competition"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}
