// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rounds.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const findAllCompletedRoundsInMatch = `-- name: FindAllCompletedRoundsInMatch :one
SELECT id, task, match, start_time, end_time, winner, status, created_at FROM rounds WHERE status = 'completed' AND match = $1 ORDER BY created_at ASC
`

type FindAllCompletedRoundsInMatchParams struct {
	Match uuid.UUID `json:"match"`
}

func (q *Queries) FindAllCompletedRoundsInMatch(ctx context.Context, arg FindAllCompletedRoundsInMatchParams) (Round, error) {
	row := q.db.QueryRow(ctx, findAllCompletedRoundsInMatch, arg.Match)
	var i Round
	err := row.Scan(
		&i.ID,
		&i.Task,
		&i.Match,
		&i.StartTime,
		&i.EndTime,
		&i.Winner,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const insertRound = `-- name: InsertRound :one
INSERT INTO rounds (
  task,
  match,
  start_time,
  end_time
) VALUES (
  $1, $2, $3, $4
) RETURNING id, task, match, start_time, end_time, winner, status, created_at
`

type InsertRoundParams struct {
	Task      uuid.UUID `json:"task"`
	Match     uuid.UUID `json:"match"`
	StartTime time.Time `json:"start_time"`
	EndTime   time.Time `json:"end_time"`
}

func (q *Queries) InsertRound(ctx context.Context, arg InsertRoundParams) (Round, error) {
	row := q.db.QueryRow(ctx, insertRound,
		arg.Task,
		arg.Match,
		arg.StartTime,
		arg.EndTime,
	)
	var i Round
	err := row.Scan(
		&i.ID,
		&i.Task,
		&i.Match,
		&i.StartTime,
		&i.EndTime,
		&i.Winner,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
