// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package repository

import (
	"context"
)

const findAllTasks = `-- name: FindAllTasks :many
SELECT id, name, details, points, created_at FROM tasks ORDER BY created_at DESC
`

func (q *Queries) FindAllTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.Query(ctx, findAllTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Details,
			&i.Points,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTask = `-- name: InsertTask :one
INSERT INTO tasks (
  name,
  details
) VALUES ( $1, $2 )
RETURNING id, name, details, points, created_at
`

type InsertTaskParams struct {
	Name    string `json:"name"`
	Details string `json:"details"`
}

func (q *Queries) InsertTask(ctx context.Context, arg InsertTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, insertTask, arg.Name, arg.Details)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Details,
		&i.Points,
		&i.CreatedAt,
	)
	return i, err
}
