// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_orders.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const deleteTaskOrder = `-- name: DeleteTaskOrder :one
DELETE FROM task_orders
WHERE task = $1 AND competition = $2
RETURNING id, competition, task, created_at
`

type DeleteTaskOrderParams struct {
	Task        uuid.UUID `json:"task"`
	Competition uuid.UUID `json:"competition"`
}

func (q *Queries) DeleteTaskOrder(ctx context.Context, arg DeleteTaskOrderParams) (TaskOrder, error) {
	row := q.db.QueryRow(ctx, deleteTaskOrder, arg.Task, arg.Competition)
	var i TaskOrder
	err := row.Scan(
		&i.ID,
		&i.Competition,
		&i.Task,
		&i.CreatedAt,
	)
	return i, err
}

const getTasksForCompetition = `-- name: GetTasksForCompetition :many
SELECT tasks.id, tasks.name, tasks.details, tasks.points, tasks.created_at FROM task_orders
JOIN tasks ON task_orders.task = tasks.id
WHERE competition = $1
ORDER BY task_orders.created_at DESC
`

type GetTasksForCompetitionParams struct {
	Competition uuid.UUID `json:"competition"`
}

func (q *Queries) GetTasksForCompetition(ctx context.Context, arg GetTasksForCompetitionParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTasksForCompetition, arg.Competition)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Details,
			&i.Points,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTaskOrder = `-- name: InsertTaskOrder :one
INSERT INTO task_orders (
  competition,
  task
) VALUES ( $1, $2 )
RETURNING id, competition, task, created_at
`

type InsertTaskOrderParams struct {
	Competition uuid.UUID `json:"competition"`
	Task        uuid.UUID `json:"task"`
}

func (q *Queries) InsertTaskOrder(ctx context.Context, arg InsertTaskOrderParams) (TaskOrder, error) {
	row := q.db.QueryRow(ctx, insertTaskOrder, arg.Competition, arg.Task)
	var i TaskOrder
	err := row.Scan(
		&i.ID,
		&i.Competition,
		&i.Task,
		&i.CreatedAt,
	)
	return i, err
}
