// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_orders.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const getTasksForCompetition = `-- name: GetTasksForCompetition :many
SELECT id, competition, task, created_at FROM task_orders
WHERE competition = $1
ORDER BY created_at DESC
`

type GetTasksForCompetitionParams struct {
	Competition uuid.UUID `json:"competition"`
}

func (q *Queries) GetTasksForCompetition(ctx context.Context, arg GetTasksForCompetitionParams) ([]TaskOrder, error) {
	rows, err := q.db.Query(ctx, getTasksForCompetition, arg.Competition)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskOrder{}
	for rows.Next() {
		var i TaskOrder
		if err := rows.Scan(
			&i.ID,
			&i.Competition,
			&i.Task,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTaskOrder = `-- name: InsertTaskOrder :one
INSERT INTO task_orders (
  competition,
  task
) VALUES ( $1, $2 )
RETURNING id, competition, task, created_at
`

type InsertTaskOrderParams struct {
	Competition uuid.UUID `json:"competition"`
	Task        uuid.UUID `json:"task"`
}

func (q *Queries) InsertTaskOrder(ctx context.Context, arg InsertTaskOrderParams) (TaskOrder, error) {
	row := q.db.QueryRow(ctx, insertTaskOrder, arg.Competition, arg.Task)
	var i TaskOrder
	err := row.Scan(
		&i.ID,
		&i.Competition,
		&i.Task,
		&i.CreatedAt,
	)
	return i, err
}
